#!/usr/bin/env python3
"""Render the §17 two-arm table as markdown, straight from results/phase10_h1/two_arm_table.csv.

The markdown in reports/CS_PHASE10_TWO_ARM.md §2 is GENERATED by this script, so no number in
it can drift from the CSV, and the CSV carries the source path and filter for every cell.

Usage: python3 code/two_arm_table_md.py > /tmp/section17.md
"""
import sys
import pandas as pd

CSV = "/workspace/results/phase10_h1/two_arm_table.csv"
ARMS = ["M1", "H1", "H1 (tierAmg_p95)", "H1 (tierA_p95)"]


def main():
    d = pd.read_csv(CSV)
    d["value"] = d["value"].astype(str)
    order, seen = [], set()
    for q in d.quantity:
        if q not in seen:
            seen.add(q); order.append(q)
    out = []
    out.append("| Quantity | M1 mouse liver (SBR fibrosis) | "
               "H1 human spleen — PRIMARY `tierAmg_p95` | H1 — frozen-literal `tierA_p95` |")
    out.append("|---|---|---|---|")
    for q in order:
        g = d[d.quantity == q]

        def val(arm):
            r = g[g.arm == arm]
            if not len(r):
                return ""
            v = r.value.iloc[0]
            n = r.note.iloc[0] if "note" in r.columns else ""
            if isinstance(n, str) and n and n != "nan" and v == "NOT_RUN":
                v = "**NOT RUN** — " + n
            return v.replace("|", "\\|")

        m = val("M1")
        h_mg = val("H1 (tierAmg_p95)") or val("H1")
        h_fine = val("H1 (tierA_p95)")
        if h_fine == h_mg:
            h_fine = "—"
        if not (m or h_mg or h_fine):
            continue
        out.append("| %s | %s | %s | %s |"
                   % (q.replace("|", "\\|"), m or "—", h_mg or "—", h_fine or "—"))
    print("\n".join(out))
    print()
    print("*Every cell above is a row of `results/phase10_h1/two_arm_table.csv`, which carries "
          "the absolute source path and the exact filter beside each value. Regenerate with "
          "`python3 code/two_arm_table.py && python3 code/two_arm_table_md.py`. "
          "Brackets on surviving fractions and amplitudes are **inter-quartile ranges across "
          "the arm's reportable fits**, not confidence intervals (PREREG correction C-4); "
          "the only genuine CIs here are on the composition-matched SFs and the A7 "
          "section-clustered means.*")


if __name__ == "__main__":
    main()
